# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20160416_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='categroy',
            new_name='category',
        ),
    ]
