# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20160416_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(default='buquan', max_length=255),
            preserve_default=False,
        ),
    ]
